### ISSUE TITLE
VaultPress Upgrade from 2.1.1 to 2.1.3 Errors

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/vaultpress#104]
**As of about a half hour ago, the 2.1.3 release has been paused, and the public release pointed back to 2.1.1.**

We've had several reports of errors in the upgrade process.  They tend to look like this:

```
[06-Aug-2020 17:41:32 UTC] PHP Fatal error: Cannot redeclare
AutomatticJetpackAutoloaderenqueue_packages_583fd9fc320cf240dae152d6e27f7b85()
(previously declared in
/path/to/wp-content/plugins/vaultpress/vendor/autoload_packages.php:126)
in
/path/tol/wp-content/plugins/vaultpress/vendor/autoload_packages.php
on line 126
```
and
```
[06-Aug-2020 18:02:01 UTC] PHP Fatal error:  Cannot redeclare Automattic\Jetpack\Autoloader\enqueue_packages_583fd9fc320cf240dae152d6e27f7b85() (previously declared in /path/to/wp-content/plugins/vaultpress/vendor/autoload_packages.php:126) in /path/to/wp-content/plugins/vaultpress/vendor/autoload_packages.php on line 126
```

(relevant paths modified to `/path/to` for anonymization)

The specified function seems to be from the /prior/ 2.1.1 version of the plugin.

https://plugins.trac.wordpress.org/browser/vaultpress/tags/2.1.1/vendor/autoload_packages.php

most notably, as the updated 2.1.3 version of the plugin doesn't even have 126 lines to the file in question:

https://plugins.trac.wordpress.org/browser/vaultpress/tags/2.1.3/vendor/autoload_packages.php

The instances where the issue arose seemed to be "stuck" in maintenance mode.  From the reports I've seen, once the `.maintenance` file in the root is removed, the upgrade has gone through and all is well.

I'm trying to sort out right now how to properly duplicate the issue.

One instance of a report of this issue:

https://wordpress.org/support/topic/2-1-3-update-not-coming-back-from-maintenance-mode/

**Comment by georgestephanis** [comment]
As a note for myself, how I'm going to attempt to debug will likely be something to the extent of adding something to the top of `wp-content/plugins/vaultpress/vendor/autoload_packages.php` like

```
file_put_contents( ABSPATH . '/wp-content/uploads/tmp.txt', wp_debug_backtrace_summary() . "\r\n", FILE_APPEND );
```

(I've not explicitly tested that, but I believe it should do the issue -- basically I'd like to confirm how the old plugin file is getting loaded the second time)

**Comment by csonnek** [comment]
Adding the two tickets (as of now) that came in to support: 
- 3204049-zen
- 3204102-zen

**Comment by jonesch** [comment]
Just noting our partner was also "stuck" in maintenance mode for about 11 minutes this afternoon. Our Slack chat [started here](https://a8c.slack.com/archives/C02C4GXMY/p1596737565258600) if that helps.

- https://seths.blog/ is hosted on Bluehost
- We found that the `.maintenance` file was removed, but it was not our team, our contractor developer, or [Bluehost](https://a8c.slack.com/archives/C5QSZKMPU/p1596737661001600) that made the change. 
- When the site came back, VaultPress was on 2.1.3.
- And here is Jetpack's story of the update: https://kibana-search.a8c.com/goto/d62b79b42091def005dbc774593e5cc3

Not sure if any of this is helpful, thought we would share though 🤷

**Comment by georgestephanis** [comment]
As a summation for anyone following this, we've had a **stellar** investigation internally from @kbrown9 tracking it down and confirming it was a result of a conditional php opcache conflict.  We're working right now on structuring a workaround.

**Comment by georgestephanis** [comment]
This has been rectified (we believe) and 2.1.4 is now released on .org which should be good.

**Comment by csonnek** [comment]
Replied to both users mentioned above and let them know the issue has been resolved.
