### ISSUE TITLE
VaultPress Large Option Size - vaultpress_service_ips_external

### ISSUE THREAD

**Issue by rickalee** [Automattic/vaultpress#111]
VaultPress IPs array coming in at 2MB and causing performance issues since autoloaded. These IPs appear to be a huge list of CloudFlare IP addresses.

Examples from list:
162.158.153.1
198.41.152.254
141.101.66.1 

Is there a hook to reset option or prevent VaultPress from adding this option? VaultPress not in use on site.

**Comment by jeherve** [comment]
@Automattic/yamato-backup-and-security Do you think you could take a look at this issue? 

Thank you!

**Comment by jwebbdev** [comment]
It looks like this option is only in use for VaultPress plugin version 1.6.6 and earlier.  Later verisons request a cidr version that's much smaller.

If both `vaultpress_service_ips_external` and `vaultpress_service_ips_external_cidr` options exist this is probably a case of a site that used to have a plugin of 1.6.6 or earlier, and the `vaultpress_service_ips_external` option can be removed.

**Comment by Stoyan0v** [comment]
We will check the version of the plugin.

Thanks for checking @jwebbdev

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
