### ISSUE TITLE
Notices: Clarify wording for “VaultPress needs your attention!”

### ISSUE THREAD

**Issue by brbrr** [Automattic/vaultpress#23]
“VaultPress needs your attention!” notice wording might be clearer. It suggests to Register VaultPress which will redirect to the ValutPress page when `View plans and pricing` primary button clicked. The page does have a way to register a key, but it does clearly highlighted.

Maybe update the CTA to something like "Register VaultPress or purchase a plan"

<img width="1360" alt="Site Stats ‹ Testing Jetpack — WordPress 2019-06-14 11-41-21" src="https://user-images.githubusercontent.com/5654161/59499214-9a3acd80-8e9f-11e9-945e-3b00625990fd.png">

**Comment by eliorivero** [comment]
cc @benhuberman to provide copy

**Comment by benhuberman** [comment]
The suggested CTA by @brbrr sounds fine to me, but perhaps we can soften/shorten the preceding sentence? E.g.:
> VaultPress needs your attention!
> To back up and secure your site, enter your registration key. [LINK] Register VaultPress or purchase a plan.
