### ISSUE TITLE
Dashboard: Increase top padding for Register button

### ISSUE THREAD

**Issue by brbrr** [Automattic/vaultpress#26]
It looks like we could add some more top padding for the “Register” button to make it match other buttons style.

<img width="1099" alt="VaultPress ‹ Testing Jetpack — WordPress 2019-06-14 12-03-09" src="https://user-images.githubusercontent.com/5654161/59499505-31a02080-8ea0-11e9-8112-f00ab15941e1.png">

**Comment by jeherve** [comment]
@eliorivero Do you think you could take a look at this?
