### ISSUE TITLE
VaultPress VP01 error hangs around even after correctly installing VaultPress

### ISSUE THREAD

**Issue by gravityrail** [Automattic/vaultpress#67]
#### Steps to reproduce the issue

1. Upgrade Jetpack to premium
2. Exit the upgrade progress screen before it has a chance to fully install VaultPress
3. Go to wp-admin - as expected, you will see the error "Please enter a valid registration key. (code: VP01)"
4. Now click "Set up" and watch the upgrade process complete
5. Go back to wp-admin

#### What I expected
No more VaultPress error

#### What happened instead
Uncloseable VaultPress error with no context or action link on all wp-admin pages - even on the VaultPress page which shows backup completing successfully!

**Screenshots**

<img width="962" alt="vaultpress-warning" src="https://user-images.githubusercontent.com/51896/68073738-7e519e80-fd50-11e9-8b78-744e2c73f322.png">

**Comment by jeherve** [comment]
I can't seem to be able to reproduce the issue on my end. Do you still have access to the site? It may be interested to look at the current VaultPress options for that site to see if they match the remote status of the site.

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
